# Generated by Django 3.2.5 on 2022-07-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soosapp', '0002_alter_address_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='rdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
