# Generated by Django 3.2.5 on 2022-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soosapp', '0003_alter_address_rdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('rdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
