# Generated by Django 3.2.5 on 2022-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soosapp', '0004_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('pwd', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=50)),
                ('rdate', models.DateTimeField(auto_now=True)),
                ('udate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
